# This rule is not used by the project k8s-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over task.task.sysd.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k8s-controller
    app.kubernetes.io/managed-by: kustomize
  name: task-admin-role
rules:
- apiGroups:
  - task.task.sysd.io
  resources:
  - tasks
  verbs:
  - '*'
- apiGroups:
  - task.task.sysd.io
  resources:
  - tasks/status
  verbs:
  - get
