apiVersion: task.task.sysd.io/v1
kind: Task
metadata:
  labels:
    app.kubernetes.io/name: k8s-controller
    app.kubernetes.io/managed-by: kustomize
  name: task-sample
spec:
  # TODO(user): Add fields here
